# -*- coding: utf-8 -*-
"""
task.py
=======
Pydantic data schemas for the .ebpearls Artifact State Registry.
"""

from __future__ import annotations

import datetime
from typing import Dict, List, Literal, Optional

from pydantic import BaseModel, Field

#: All valid task lifecycle statuses in the SPOQ pipeline.
TaskStatus = Literal[
    "planned",
    "building",
    "built",
    "evaluating",
    "evaluate_failed",
    "repairing",
    "passed",
    "blocked",
]


class TaskArtifacts(BaseModel):
    """File-system paths of artifacts generated for a single pipeline task."""

    contract: Optional[str] = None
    """Relative path to the task contract / implementation plan Markdown file."""

    journal: Optional[str] = None
    """Relative path to the code-evaluator journal Markdown file."""

    schema_file: Optional[str] = None
    """Relative path to the exported API schema file (GraphQL SDL / OpenAPI JSON)."""

    verification: Optional[str] = None
    """Relative path to the contract-verifier result file, if produced."""


class TaskArtifactState(BaseModel):
    """
    Per-task artifact registry entry stored in ``.ebpearls/Epic-{id}/state.json``.

    Stores only the information agents need to make resume/skip/repair decisions.
    The authoritative pipeline position is held by the LangGraph checkpoint
    (Postgres); this entry is a human-readable *projection* of that state.
    """

    task_id: str
    """Unique identifier for the task (e.g. ``contract-41831``)."""

    platform: str
    """Target platform for this task (``api`` | ``flutter`` | ``web``)."""

    status: TaskStatus = "planned"
    """Current lifecycle phase of the task."""

    artifacts: TaskArtifacts = Field(default_factory=TaskArtifacts)
    """Paths to files generated by the pipeline for this task."""

    repair_iteration: int = Field(default=0, ge=0)
    """Number of repair cycles attempted so far. Blocked after >= MAX_REPAIR_ITERATIONS."""

    evaluation_avg: Optional[float] = Field(default=None, ge=0.0, le=100.0)
    """Average of the 10 evaluation metrics from the last code-evaluator run."""

    evaluation_min: Optional[int] = Field(default=None, ge=0, le=100)
    """Minimum of the 10 evaluation metrics from the last code-evaluator run."""

    updated_at: datetime.datetime = Field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))
    """ISO-8601 UTC timestamp of the last status change."""

    @property
    def is_terminal(self) -> bool:
        """Return True when the task reached a non-retryable terminal state."""
        return self.status in ("passed", "blocked")

    @property
    def needs_repair(self) -> bool:
        """Return True when the task failed evaluation and repair is warranted."""
        return self.status == "evaluate_failed"


class EpicStateSnapshot(BaseModel):
    """
    Artifact registry for a single SPOQ epic.

    Written to ``.ebpearls/Epic-{id}/state.json`` by the orchestration pipeline
    and read by OpenCode agents during pre-flight checks to decide whether to
    skip already-generated artifacts or resume from an intermediate state.

    This model is intentionally lightweight — it stores only the fields an agent
    requires for its resume decision, not the full LangGraph ``GraphState``.
    """

    epic_id: str
    """Identifier of the epic (e.g. ``Epic-44445``)."""

    space_name: str
    """Project workspace name — used to resolve the absolute `.ebpearls/` path."""

    tasks: Dict[str, TaskArtifactState] = Field(default_factory=dict)
    """Mapping of task ID → per-task artifact state."""

    last_updated: datetime.datetime = Field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))
    """ISO-8601 UTC timestamp of the last write to this snapshot."""

    schema_version: str = "1"
    """Schema version for future forward-compatibility checks."""

    def get_task(self, task_id: str) -> Optional[TaskArtifactState]:
        """Return the state for *task_id*, or ``None`` if not yet registered."""
        tasks: Dict[str, TaskArtifactState] = self.tasks  # pylint: disable=no-member
        return tasks.get(task_id)

    def upsert_task(self, task_state: TaskArtifactState) -> "EpicStateSnapshot":
        """
        Return a new snapshot with *task_state* inserted or replaced.

        Uses immutable copy semantics to stay consistent with Pydantic v2 patterns.
        """
        tasks: Dict[str, TaskArtifactState] = self.tasks  # pylint: disable=no-member
        updated_tasks = {**tasks, task_state.task_id: task_state}
        return self.model_copy(
            update={
                "tasks": updated_tasks,
                "last_updated": datetime.datetime.now(datetime.timezone.utc),
            }
        )

    def pending_tasks(self) -> List[TaskArtifactState]:
        """Return all tasks not yet in a terminal state, sorted by task_id."""
        tasks: Dict[str, TaskArtifactState] = self.tasks  # pylint: disable=no-member
        return sorted(
            [t for t in tasks.values() if not t.is_terminal],
            key=lambda t: t.task_id,
        )
